"""
em-app: A Python package for Electromagnetic applications using MTFLibrary.

This package provides tools for calculating and visualizing magnetic fields
generated by current-carrying coils using the Biot-Savart law.
"""

from .biot_savart import serial_biot_savart, mpi_biot_savart
from .currentcoils import Coil, RingCoil, RectangularCoil
from .magneticfield import Bvec, Bfield

__all__ = [
    "serial_biot_savart",
    "mpi_biot_savart",
    "Coil",
    "RingCoil",
    "RectangularCoil",
    "StraightWire",
    "Bvec",
    "Bfield",
]

try:
    from mtflib import mtf

    # Initialize mtf with default values if it has not been initialized yet.
    # This prevents errors when the library is used without explicit initialization.
    if not getattr(mtf, "_INITIALIZED", False):
        mtf.initialize_mtf(max_order=5, max_dimension=10)
except ImportError:
    # mtflib is not installed, but the package can still be used with numerical data.
    pass
