"""
em-app: A Python package for Electromagnetic applications using MTFLibrary.

This package provides tools for calculating and visualizing magnetic fields
generated by current-carrying coils using the Biot-Savart law.
"""

from .solvers import serial_biot_savart, mpi_biot_savart, calculate_b_field
from .sources import Coil, RingCoil, RectangularCoil, StraightWire
from .vectors_and_fields import Vector, FieldVector, VectorField, VectorFieldGrid
from .plotting import plot_1d_field, plot_2d_field, plot_field_vectors_3d

__all__ = [
    "serial_biot_savart",
    "mpi_biot_savart",
    "calculate_b_field",
    "Coil",
    "RingCoil",
    "RectangularCoil",
    "StraightWire",
    "Vector",
    "FieldVector",
    "VectorField",
    "VectorFieldGrid",
    "plot_1d_field",
    "plot_2d_field",
    "plot_field_vectors_3d",
]
