"""
em-app: A Python package for Electromagnetic applications using MTFLibrary.

This package provides tools for calculating and visualizing magnetic fields
generated by current-carrying coils using the Biot-Savart law.
"""

from .plotting import plot_1d_field, plot_2d_field, plot_field_vectors_3d
from .solvers import calculate_b_field, mpi_biot_savart, serial_biot_savart
from .sources import Coil, RectangularCoil, RingCoil, StraightWire
from .vector_fields import FieldVector, Vector, VectorField, VectorFieldGrid

__all__ = [
    "serial_biot_savart",
    "mpi_biot_savart",
    "calculate_b_field",
    "Coil",
    "RingCoil",
    "RectangularCoil",
    "StraightWire",
    "Vector",
    "FieldVector",
    "VectorField",
    "VectorFieldGrid",
    "plot_1d_field",
    "plot_2d_field",
    "plot_field_vectors_3d",
]
